// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* Generated by typesafe-i18n. Do not edit — run `bun run i18n:generate`. */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'ru'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	chat: {
		approval: {
			reason: {
				plan: {
					shellNotReadOnly: string
					mutatingOperation: string
				}
				acceptEdits: {
					outsideAllowlist: string
				}
				auto: {
					mcpTool: RequiredParams<'tool'>
					forkBomb: string
					blockDeviceRedirect: string
					recursiveDelete: string
					windowsDelete: string
					filesystemDestroy: string
					deviceWrite: string
					permissionSweep: string
					privilegeEscalation: string
					powerControl: string
					killAll: string
					rawNetwork: string
					upload: string
					remoteCopy: string
					secretOverNetwork: string
					pipeToShell: string
					writeSecret: string
					writeGitDir: string
					writeOutsideProject: string
				}
			}
		}
		languagePicker: {
			label: string
			matchGlobal: string
		}
		review: {
			fileCount: RequiredParams<'count'>
			filesChanged: string
			turnSuffix: RequiredParams<'count'>
		}
		tools: {
			moreLines: RequiredParams<'count'>
			editCount: RequiredParams<'count'>
		}
		planSnapshot: {
			earlierSteps: RequiredParams<'count'>
			moreSteps: RequiredParams<'count'>
		}
		planCard: {
			commentsPending: RequiredParams<'count'>
		}
		planComments: {
			count: RequiredParams<'count'>
		}
		ask: {
			sendChoices: RequiredParams<'count'>
		}
	}
	common: {
		cancel: string
		close: string
		save: string
		remove: string
		retry: string
		dismiss: string
		error: {
			generic: string
			host: {
				notFound: string
				invalidRequest: string
				unknownCommand: string
				registryFailed: string
				pathEscape: string
				notARepo: string
				lspFailed: string
				lspUnknownKey: string
				lspMethodNotAllowed: string
				illegalName: string
				gitNotFound: string
				gitFailed: string
				fsFailed: string
				fsExists: string
				forbidden: string
			}
			hostEvent: string
			promptError: string
			transport: {
				authFailed: string
				disconnected: string
				timedOut: string
			}
		}
		diff: {
			commitFiles: RequiredParams<'count'>
			revertAllConfirm: RequiredParams<'count'>
		}
		files: {
			confirmDeleteTitle: RequiredParams<'count'>
			moreItems: RequiredParams<'count'>
		}
	}
	editor: {
	}
	format: {
		justNow: string
		duration: {
			seconds: RequiredParams<'value'>
			minutesSeconds: RequiredParams<'minutes' | 'seconds'>
		}
	}
	git: {
		notify: {
			remoteBranchMeta: RequiredParams<'branch' | 'reason' | 'remote'>
			viewLog: string
			commit: {
				tag: string
				title: RequiredParams<'branch'>
				titleNoBranch: string
				meta: RequiredParams<'add' | 'count' | 'del' | 'sha' | 'when'>
				failedTitle: string
			}
			push: {
				tag: string
				tagRejected: string
				tagFailed: string
				title: RequiredParams<'branch' | 'remote'>
				sentUpstream: RequiredParams<'count'>
				upToDate: string
				failedTitle: RequiredParams<'remote'>
				reason: {
					nonFastForward: string
					noUpstream: string
					authFailed: string
					rejected: string
					unknown: string
				}
			}
			pull: {
				tag: string
				tagFailed: string
				title: RequiredParams<'branch' | 'remote'>
				rebased: string
				fastForwarded: string
				failedTitle: RequiredParams<'remote'>
				reason: {
					conflict: string
					noUpstream: string
					authFailed: string
					unknown: string
				}
			}
			rollback: {
				tag: string
				title: string
				body: RequiredParams<'count'>
				failedTitle: string
			}
			stash: {
				tag: string
				title: string
				bodySelected: RequiredParams<'count'>
				bodyAll: string
				failedTitle: string
				reason: {
					noChanges: string
					unknown: string
				}
			}
			stashPop: {
				tag: string
				title: string
				body: string
				failedTitle: string
				reason: {
					emptyStack: string
					conflict: string
					unknown: string
				}
			}
			refresh: {
				title: string
				body: string
			}
		}
		reason: {
			nonFastForward: string
			noUpstream: string
			authFailed: string
			rejected: string
			unknown: string
			conflict: string
		}
		logWindowTitle: string
		actions: {
			view: string
			undo: string
			push: string
			apply: string
			pullRebase: string
			forcePush: string
		}
		errors: {
			loadBranches: string
			checkoutBranch: string
			createBranch: string
			readStatus: string
			initRepo: string
			openPrUrl: string
			undo: string
			resolveCommitUrl: string
			copy: string
		}
		store: {
			noFilesSelected: string
			copiedToClipboard: RequiredParams<'name'>
		}
	}
	intro: {
		templates: {
			'fix-failing-test': {
				title: string
				blurb: string
				body: string
			}
			'implement-a-spec': {
				title: string
				blurb: string
				body: string
			}
			'refactor-in-place': {
				title: string
				blurb: string
				body: string
			}
			'write-the-docs': {
				title: string
				blurb: string
				body: string
			}
			'review-a-pr': {
				title: string
				blurb: string
				body: string
			}
			'bisect-a-regression': {
				title: string
				blurb: string
				body: string
			}
		}
	}
	plan: {
		continuation: string
		comments: {
			leadIn: string
			closing: string
		}
		panel: {
			inProgressFallback: string
		}
	}
	sessions: {
		filter: {
			selectedCount: RequiredParams<'count'>
		}
	}
	settings: {
		appearance: {
			language: {
				label: string
				desc: string
				hint: string
			}
		}
		agents: {
			responseLanguage: {
				label: string
				desc: string
				matchUi: string
			}
		}
		skills: {
			scanFoundToast: RequiredParams<'count'>
			installedTitle: RequiredParams<'count'>
			scanFoundLabel: RequiredParams<'count'>
		}
	}
	shell: {
		topBar: {
			backToStart: string
			leftPanel: {
				show: string
				hide: string
			}
			bottomPanel: {
				show: string
				hide: string
			}
			rightPanel: {
				show: string
				hide: string
			}
		}
		settings: {
			open: string
			shortcutTooltip: RequiredParams<'mod'>
		}
		terminal: {
			toggle: string
			shortcutTooltip: RequiredParams<'mod'>
		}
		leftRail: {
			label: string
			tabs: string
			sessions: string
			files: string
		}
		rightPane: {
			label: string
			tabs: string
			session: string
			git: string
			context: string
		}
		screenSwitcher: {
			label: string
			sessionGate: string
			session: string
			editor: string
			diff: string
			blank: string
		}
		resize: {
			leftRail: string
			rightPane: string
			terminalPanel: string
		}
		windowControls: {
			minimize: string
			maximize: string
			restore: string
		}
		footer: {
			screen: string
		}
		sessionPane: {
			loading: string
		}
		components: {
			confirmDialog: {
				confirm: string
			}
			stepper: {
				increase: RequiredParams<'label'>
				decrease: RequiredParams<'label'>
				increaseBare: string
				decreaseBare: string
			}
			chipPicker: {
				header: string
			}
		}
	}
	terminal: {
	}
}

export type TranslationFunctions = {
	chat: {
		approval: {
			reason: {
				plan: {
					shellNotReadOnly: () => LocalizedString
					mutatingOperation: () => LocalizedString
				}
				acceptEdits: {
					outsideAllowlist: () => LocalizedString
				}
				auto: {
					mcpTool: (arg: { tool: string }) => LocalizedString
					forkBomb: () => LocalizedString
					blockDeviceRedirect: () => LocalizedString
					recursiveDelete: () => LocalizedString
					windowsDelete: () => LocalizedString
					filesystemDestroy: () => LocalizedString
					deviceWrite: () => LocalizedString
					permissionSweep: () => LocalizedString
					privilegeEscalation: () => LocalizedString
					powerControl: () => LocalizedString
					killAll: () => LocalizedString
					rawNetwork: () => LocalizedString
					upload: () => LocalizedString
					remoteCopy: () => LocalizedString
					secretOverNetwork: () => LocalizedString
					pipeToShell: () => LocalizedString
					writeSecret: () => LocalizedString
					writeGitDir: () => LocalizedString
					writeOutsideProject: () => LocalizedString
				}
			}
		}
		languagePicker: {
			label: () => LocalizedString
			matchGlobal: () => LocalizedString
		}
		review: {
			fileCount: (arg: { count: number }) => LocalizedString
			filesChanged: (arg: { count: number | string | boolean }) => LocalizedString
			turnSuffix: (arg: { count: number }) => LocalizedString
		}
		tools: {
			moreLines: (arg: { count: number }) => LocalizedString
			editCount: (arg: { count: number }) => LocalizedString
		}
		planSnapshot: {
			earlierSteps: (arg: { count: number }) => LocalizedString
			moreSteps: (arg: { count: number }) => LocalizedString
		}
		planCard: {
			commentsPending: (arg: { count: number }) => LocalizedString
		}
		planComments: {
			count: (arg: { count: number }) => LocalizedString
		}
		ask: {
			sendChoices: (arg: { count: number }) => LocalizedString
		}
	}
	common: {
		cancel: () => LocalizedString
		close: () => LocalizedString
		save: () => LocalizedString
		remove: () => LocalizedString
		retry: () => LocalizedString
		dismiss: () => LocalizedString
		error: {
			generic: () => LocalizedString
			host: {
				notFound: () => LocalizedString
				invalidRequest: () => LocalizedString
				unknownCommand: () => LocalizedString
				registryFailed: () => LocalizedString
				pathEscape: () => LocalizedString
				notARepo: () => LocalizedString
				lspFailed: () => LocalizedString
				lspUnknownKey: () => LocalizedString
				lspMethodNotAllowed: () => LocalizedString
				illegalName: () => LocalizedString
				gitNotFound: () => LocalizedString
				gitFailed: () => LocalizedString
				fsFailed: () => LocalizedString
				fsExists: () => LocalizedString
				forbidden: () => LocalizedString
			}
			hostEvent: () => LocalizedString
			promptError: () => LocalizedString
			transport: {
				authFailed: () => LocalizedString
				disconnected: () => LocalizedString
				timedOut: () => LocalizedString
			}
		}
		diff: {
			commitFiles: (arg: { count: number }) => LocalizedString
			revertAllConfirm: (arg: { count: number }) => LocalizedString
		}
		files: {
			confirmDeleteTitle: (arg: { count: number }) => LocalizedString
			moreItems: (arg: { count: number }) => LocalizedString
		}
	}
	editor: {
	}
	format: {
		justNow: () => LocalizedString
		duration: {
			seconds: (arg: { value: string }) => LocalizedString
			minutesSeconds: (arg: { minutes: string, seconds: string }) => LocalizedString
		}
	}
	git: {
		notify: {
			remoteBranchMeta: (arg: { branch: string, reason: string, remote: string }) => LocalizedString
			viewLog: () => LocalizedString
			commit: {
				tag: () => LocalizedString
				title: (arg: { branch: string }) => LocalizedString
				titleNoBranch: () => LocalizedString
				meta: (arg: { add: number, count: number, del: number, sha: string, when: string }) => LocalizedString
				failedTitle: () => LocalizedString
			}
			push: {
				tag: () => LocalizedString
				tagRejected: () => LocalizedString
				tagFailed: () => LocalizedString
				title: (arg: { branch: string, remote: string }) => LocalizedString
				sentUpstream: (arg: { count: number }) => LocalizedString
				upToDate: () => LocalizedString
				failedTitle: (arg: { remote: string }) => LocalizedString
				reason: {
					nonFastForward: () => LocalizedString
					noUpstream: () => LocalizedString
					authFailed: () => LocalizedString
					rejected: () => LocalizedString
					unknown: () => LocalizedString
				}
			}
			pull: {
				tag: () => LocalizedString
				tagFailed: () => LocalizedString
				title: (arg: { branch: string, remote: string }) => LocalizedString
				rebased: () => LocalizedString
				fastForwarded: () => LocalizedString
				failedTitle: (arg: { remote: string }) => LocalizedString
				reason: {
					conflict: () => LocalizedString
					noUpstream: () => LocalizedString
					authFailed: () => LocalizedString
					unknown: () => LocalizedString
				}
			}
			rollback: {
				tag: () => LocalizedString
				title: () => LocalizedString
				body: (arg: { count: number }) => LocalizedString
				failedTitle: () => LocalizedString
			}
			stash: {
				tag: () => LocalizedString
				title: () => LocalizedString
				bodySelected: (arg: { count: number }) => LocalizedString
				bodyAll: () => LocalizedString
				failedTitle: () => LocalizedString
				reason: {
					noChanges: () => LocalizedString
					unknown: () => LocalizedString
				}
			}
			stashPop: {
				tag: () => LocalizedString
				title: () => LocalizedString
				body: () => LocalizedString
				failedTitle: () => LocalizedString
				reason: {
					emptyStack: () => LocalizedString
					conflict: () => LocalizedString
					unknown: () => LocalizedString
				}
			}
			refresh: {
				title: () => LocalizedString
				body: () => LocalizedString
			}
		}
		reason: {
			nonFastForward: () => LocalizedString
			noUpstream: () => LocalizedString
			authFailed: () => LocalizedString
			rejected: () => LocalizedString
			unknown: () => LocalizedString
			conflict: () => LocalizedString
		}
		logWindowTitle: () => LocalizedString
		actions: {
			view: () => LocalizedString
			undo: () => LocalizedString
			push: () => LocalizedString
			apply: () => LocalizedString
			pullRebase: () => LocalizedString
			forcePush: () => LocalizedString
		}
		errors: {
			loadBranches: () => LocalizedString
			checkoutBranch: () => LocalizedString
			createBranch: () => LocalizedString
			readStatus: () => LocalizedString
			initRepo: () => LocalizedString
			openPrUrl: () => LocalizedString
			undo: () => LocalizedString
			resolveCommitUrl: () => LocalizedString
			copy: () => LocalizedString
		}
		store: {
			noFilesSelected: () => LocalizedString
			copiedToClipboard: (arg: { name: string }) => LocalizedString
		}
	}
	intro: {
		templates: {
			'fix-failing-test': {
				title: () => LocalizedString
				blurb: () => LocalizedString
				body: () => LocalizedString
			}
			'implement-a-spec': {
				title: () => LocalizedString
				blurb: () => LocalizedString
				body: () => LocalizedString
			}
			'refactor-in-place': {
				title: () => LocalizedString
				blurb: () => LocalizedString
				body: () => LocalizedString
			}
			'write-the-docs': {
				title: () => LocalizedString
				blurb: () => LocalizedString
				body: () => LocalizedString
			}
			'review-a-pr': {
				title: () => LocalizedString
				blurb: () => LocalizedString
				body: () => LocalizedString
			}
			'bisect-a-regression': {
				title: () => LocalizedString
				blurb: () => LocalizedString
				body: () => LocalizedString
			}
		}
	}
	plan: {
		continuation: () => LocalizedString
		comments: {
			leadIn: () => LocalizedString
			closing: () => LocalizedString
		}
		panel: {
			inProgressFallback: () => LocalizedString
		}
	}
	sessions: {
		filter: {
			selectedCount: (arg: { count: number }) => LocalizedString
		}
	}
	settings: {
		appearance: {
			language: {
				label: () => LocalizedString
				desc: () => LocalizedString
				hint: () => LocalizedString
			}
		}
		agents: {
			responseLanguage: {
				label: () => LocalizedString
				desc: () => LocalizedString
				matchUi: () => LocalizedString
			}
		}
		skills: {
			scanFoundToast: (arg: { count: number }) => LocalizedString
			installedTitle: (arg: { count: number }) => LocalizedString
			scanFoundLabel: (arg: { count: number }) => LocalizedString
		}
	}
	shell: {
		topBar: {
			backToStart: () => LocalizedString
			leftPanel: {
				show: () => LocalizedString
				hide: () => LocalizedString
			}
			bottomPanel: {
				show: () => LocalizedString
				hide: () => LocalizedString
			}
			rightPanel: {
				show: () => LocalizedString
				hide: () => LocalizedString
			}
		}
		settings: {
			open: () => LocalizedString
			shortcutTooltip: (arg: { mod: string }) => LocalizedString
		}
		terminal: {
			toggle: () => LocalizedString
			shortcutTooltip: (arg: { mod: string }) => LocalizedString
		}
		leftRail: {
			label: () => LocalizedString
			tabs: () => LocalizedString
			sessions: () => LocalizedString
			files: () => LocalizedString
		}
		rightPane: {
			label: () => LocalizedString
			tabs: () => LocalizedString
			session: () => LocalizedString
			git: () => LocalizedString
			context: () => LocalizedString
		}
		screenSwitcher: {
			label: () => LocalizedString
			sessionGate: () => LocalizedString
			session: () => LocalizedString
			editor: () => LocalizedString
			diff: () => LocalizedString
			blank: () => LocalizedString
		}
		resize: {
			leftRail: () => LocalizedString
			rightPane: () => LocalizedString
			terminalPanel: () => LocalizedString
		}
		windowControls: {
			minimize: () => LocalizedString
			maximize: () => LocalizedString
			restore: () => LocalizedString
		}
		footer: {
			screen: () => LocalizedString
		}
		sessionPane: {
			loading: () => LocalizedString
		}
		components: {
			confirmDialog: {
				confirm: () => LocalizedString
			}
			stepper: {
				increase: (arg: { label: string }) => LocalizedString
				decrease: (arg: { label: string }) => LocalizedString
				increaseBare: () => LocalizedString
				decreaseBare: () => LocalizedString
			}
			chipPicker: {
				header: () => LocalizedString
			}
		}
	}
	terminal: {
	}
}

export type Formatters = {}
