// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* Generated by typesafe-i18n. Do not edit — run `bun run i18n:generate`. */

import { initFormatters } from './formatters.ts'
import type { Locales, Translations } from './i18n-types.ts'
import { loadedFormatters, loadedLocales, locales } from './i18n-util.ts'

import en from './en/index.ts'
import ru from './ru/index.ts'

const localeTranslations = {
	en,
	ru,
}

export const loadLocale = (locale: Locales): void => {
	if (loadedLocales[locale]) return

	loadedLocales[locale] = localeTranslations[locale] as unknown as Translations
	loadFormatters(locale)
}

export const loadAllLocales = (): void => locales.forEach(loadLocale)

export const loadFormatters = (locale: Locales): void =>
	void (loadedFormatters[locale] = initFormatters(locale))
